language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
#install: 
install:
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script:
  - nosetests
#after_success:
#  coveralls
notifications:
  email: false
